/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const chainNames = require("./src/sidebars/chains.json");
const {
  versionSelector,
  versionCrumb,
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");
const { chainSelector } = require("./src/sidebars/utils");

const sidebars = {
  aptos: [
    {
      type: "html",
      defaultStyle: true,
      value: chainSelector(chainNames),
      className: "version-button",
    },
    {
      type: "doc",
      label: "Overview",
      id: "intro",
    },
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
        title: "Getting Started",
        slug: "/getting-started",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },
    {
      type: "category",
      label: "Aptos API Reference",
      link: {
        type: "generated-index",
        title: "Aptos API",
        slug: "/category/aptos-api",
      },
      items: [
        {
          type: "doc",
          id: "rate-limit",
        },
        {
          type: "doc",
          id: "authentication",
        },
        // require("./docs/aptos/sidebar.js"),
        require("./docs/aptos/block-sidebar.js"),
        require("./docs/aptos/event-sidebar.js"),
        require("./docs/aptos/nft-sidebar.js"),
        require("./docs/aptos/token-sidebar.js"),
        require("./docs/aptos/transaction-sidebar.js"),
      ],
    },
  ],
  evm: [
    {
      type: "html",
      defaultStyle: true,
      value: chainSelector(chainNames),
      className: "version-button",
    },
    {
      type: "category",
      label: "EVM API",
      link: {
        type: "generated-index",
        title: "EVM API",
        slug: "/category/evm-api",
      },
      items: require("./docs/evm/sidebar.js"),
    },
  ],
  sui: [
    {
      type: "html",
      defaultStyle: true,
      value: chainSelector(chainNames),
      className: "version-button",
    },
    {
      type: "category",
      label: "SUI API",
      link: {
        type: "generated-index",
        title: "SUI API",
        slug: "/category/sui-api",
      },
      items: require("./docs/sui/sidebar.js"),
    },
  ],
};

module.exports = sidebars;
